// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mode_matricize_cpp
arma::mat mode_matricize_cpp(const NumericVector& A, const int d);
RcppExport SEXP _BayesCoMET_mode_matricize_cpp(SEXP ASEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(mode_matricize_cpp(A, d));
    return rcpp_result_gen;
END_RCPP
}
// revkronAll_cpp
arma::mat revkronAll_cpp(const List& Glist);
RcppExport SEXP _BayesCoMET_revkronAll_cpp(SEXP GlistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type Glist(GlistSEXP);
    rcpp_result_gen = Rcpp::wrap(revkronAll_cpp(Glist));
    return rcpp_result_gen;
END_RCPP
}
// revkronLOO_cpp
arma::mat revkronLOO_cpp(const List& Glist, const int d);
RcppExport SEXP _BayesCoMET_revkronLOO_cpp(SEXP GlistSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type Glist(GlistSEXP);
    Rcpp::traits::input_parameter< const int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(revkronLOO_cpp(Glist, d));
    return rcpp_result_gen;
END_RCPP
}
// khatri_rao_comet_cpp
arma::mat khatri_rao_comet_cpp(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _BayesCoMET_khatri_rao_comet_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(khatri_rao_comet_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// cpB_cpp
NumericVector cpB_cpp(const List& factorsList);
RcppExport SEXP _BayesCoMET_cpB_cpp(SEXP factorsListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type factorsList(factorsListSEXP);
    rcpp_result_gen = Rcpp::wrap(cpB_cpp(factorsList));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesCoMET_mode_matricize_cpp", (DL_FUNC) &_BayesCoMET_mode_matricize_cpp, 2},
    {"_BayesCoMET_revkronAll_cpp", (DL_FUNC) &_BayesCoMET_revkronAll_cpp, 1},
    {"_BayesCoMET_revkronLOO_cpp", (DL_FUNC) &_BayesCoMET_revkronLOO_cpp, 2},
    {"_BayesCoMET_khatri_rao_comet_cpp", (DL_FUNC) &_BayesCoMET_khatri_rao_comet_cpp, 2},
    {"_BayesCoMET_cpB_cpp", (DL_FUNC) &_BayesCoMET_cpB_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesCoMET(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
