# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mode_matrix_cpp <- function(A, d) {
    .Call('_BayesCoMET_mode_matrix_cpp', PACKAGE = 'BayesCoMET', A, d)
}

revkronAll_cpp <- function(Glist) {
    .Call('_BayesCoMET_revkronAll_cpp', PACKAGE = 'BayesCoMET', Glist)
}

LOOrevkron_cpp <- function(Glist, d) {
    .Call('_BayesCoMET_LOOrevkron_cpp', PACKAGE = 'BayesCoMET', Glist, d)
}

