# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mode_matricize_cpp <- function(A, d) {
    .Call(`_BayesCoMET_mode_matricize_cpp`, A, d)
}

revkronAll_cpp <- function(Glist) {
    .Call(`_BayesCoMET_revkronAll_cpp`, Glist)
}

revkronLOO_cpp <- function(Glist, d) {
    .Call(`_BayesCoMET_revkronLOO_cpp`, Glist, d)
}

khatri_rao_comet_cpp <- function(A, B) {
    .Call(`_BayesCoMET_khatri_rao_comet_cpp`, A, B)
}

cpB_cpp <- function(factorsList) {
    .Call(`_BayesCoMET_cpB_cpp`, factorsList)
}

